# Generated by Django 3.2.7 on 2021-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
